[package]
name = "mod-template"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
game = { path = "../game" }
client = { path = "../client" }

# Used to make sure main is sync
static_assertions = "1.1.0"